include: package:very_good_analysis/analysis_options.5.0.0.yaml
analyzer:
  exclude: [build/**, lib/**.freezed.dart, packages/**.freezed.dart, lib/**.g.dart, packages/**.g.dart]
linter:
  rules:
    public_member_api_docs: false
    avoid_redundant_argument_values: false
