name: wast_not
sdkPath: .fvm/flutter_sdk

packages:
  - packages/*
  - app

scripts:
  analyze:
    exec: fvm dart analyze .

  generate:
    exec: fvm dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner

  format:
    exec: fvm dart fix ./lib --apply && fvm dart format ./lib

  pull:
    description: Pull latest changes from the remote repository
    run: git pull --recurse-submodules
  
  submodules-pull-latest:
    description: Pull latest changes from submodules. It resets the submodules to their latest commit.
    run: git submodule update --recursive --remote
  
  submodules-init:
    description: Initialize git submodules
    run: git submodule update --init --recursive
