name: waste_not
description: Waste Not App
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  a2f_sdk: 1.0.0
  flext: ^0.1.0
  flutter: { sdk: flutter }
  flutter_bloc: ^8.1.3
  flutter_localizations: { sdk: flutter }
  get_it: ^7.6.4
  go_router: ^12.0.1
  intl: ^0.18.0
  items_repository: { path: ../packages/items_repository }
  mobile_scanner: ^3.5.1
  path: ^1.8.3
  products_repository: { path: ../packages/products_repository }
  shimmer: ^3.0.0
  storages_repository: { path: ../packages/storages_repository }
  uuid: ^4.2.1

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test: { sdk: flutter }
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
