name: items_repository
description: Items repository is in charge of handle the user items.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  a2f_sdk: 1.0.0
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  products_repository:
    path: ../products_repository
  storages_repository:
    path: ../storages_repository
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mockito: ^5.4.4
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
